### ISSUE TITLE
Token not being added to in-scope requests

### ISSUE THREAD

**Issue by KernowSec** [nccgroup/jwt-reauth#2]
Hey,

Cool project. One thing ive noticed that, following your guide the token doesnt get added to any in-scope url set in the JWT Reauth -> scope.

Not sure whats happening, no errors in logs.

**Comment by ngregoire** [comment]
It works for me. Make sure that:
- the `Active` and `Prefix` checkboxes are checked
- the scope URL includes a port number, even if the default one (i.e. 443 for HTTPS) is used
