### ISSUE TITLE
Some logs don't appear in the Event Log

### ISSUE THREAD

**Issue by ngregoire** [nccgroup/jwt-reauth#3]
Hello!

Some logs don't appear in the extension's Event Log. I assume that's because they include a newline:
https://github.com/nccgroup/jwt-reauth/blob/c377699e6e84ba6ab5e409c717757c659ff9027f/src/com/nccgroup/jwtreauth/TokenListener.java#L114
https://github.com/nccgroup/jwt-reauth/blob/c377699e6e84ba6ab5e409c717757c659ff9027f/src/com/nccgroup/jwtreauth/TokenListener.java#L123

**Comment by tritoke** [comment]
Could you give some context around when they don't appear?

- do they appear as an empty row for example?

There is nothing innate about having a newline that stops them from being added, the code path is the same for both. I do agree that having a newline is odd and is a relic of when I was originally logging to just a raw text window.

**Comment by ngregoire** [comment]
My bad, I confused the log filters (the three buttons) and the log level (the drop down menu in "Settings").

Everything works fine, I'll close the issue.
