### ISSUE TITLE
Overly strict scope URL

### ISSUE THREAD

**Issue by ngregoire** [nccgroup/jwt-reauth#4]
Hello!

1) Defining a scope URL from the contextual menu works, but the "Prefix" checkbox is by default disabled. I think that enabling it would better match real-life use-cases:
https://github.com/nccgroup/jwt-reauth/blob/c377699e6e84ba6ab5e409c717757c659ff9027f/src/com/nccgroup/jwtreauth/ui/scope/ScopeTable.java#L140

2) Scope URLs must include a port number, even if the default one (i.e. 443 for HTTPS)  is used. That's counter-intuitive, especially when users type the URL (by opposition to using the contextual menu entry `Send to JWT re-auth (add to scope)`)

**Comment by tritoke** [comment]
I agree with your first point, it does seem like a more intuitive decision to want a prefix by default.

The second point is unfortunate as its just symptom of the fact I compare them as strings in the `inScope` function.

Annoyingly I've actually already implemented the correct behaviour:
https://github.com/nccgroup/jwt-reauth/blob/c377699e6e84ba6ab5e409c717757c659ff9027f/src/com/nccgroup/jwtreauth/utils/UrlComparison.java#L35
